### ISSUE TITLE
Does not work with JSON

### ISSUE THREAD

**Issue by gryphonmyers** [piotr-cz/cockpit-import#2]
![image](https://cloud.githubusercontent.com/assets/5785304/13784968/abb07d34-ea8e-11e5-8161-86eea6495e0b.png)

If I select a valid JSON file to import, it fails to correctly identify "columns." 

Is it expecting a particular structure?

**Comment by piotr-cz** [comment]
Looks like the JSON import is broken in v1.1.0.
You may try downgrading to v1.0.0-rc.1 if you are in a hurry

**Comment by piotr-cz** [comment]
Okay, [this line](https://github.com/piotr-cz/cockpit-import/blob/v1.1.0/assets/js/index.js#L284) should be

``` JS
parseFn = parser.json;
```

It breaks location field, because it's passing object and filter expects string to geolocate

**Comment by gryphonmyers** [comment]
Ok I can mess around with it and do a PR when I get it working thanks

**Comment by piotr-cz** [comment]
I got it, but will commit tomorrow.

**Comment by piotr-cz** [comment]
Should be fixed in 87b69befe303151aa617f045dcdbeb9066366f14, please confirm.

Besides fixing relation to json parser I reset filters to _noop_ type, as files exported from Cockpit should be already properly parsed.

**Comment by gryphonmyers** [comment]
Yes that appears to have resolved it
